# 04 반드시 알아야 하는 파이토치 스킬

## 4.1 텐서

### 4.1.1 Scalar

In [29]:
# 텐서 메서드를 이용한 스칼라 값 정의
import torch
scalar1 = torch.tensor([1.])
print(scalar1)
scalar2 = torch.tensor([3.])
print(scalar2)

tensor([1.])
tensor([3.])


In [6]:
# 스칼라 값 간의 사칙연산
add_scalar = scalar1 + scalar2
print(add_scalar)

tensor([4.])


### 4.1.2 Vector

### 4.1.3 행렬

### 4.1.4 텐서

## 4.2 Autograd

In [9]:
import torch

# Device 확인
if torch.cuda.is_available():
    DEVICE = torch.device('cuda')
else:
    DEVICE = torch.device('cpu')
print(DEVICE)

cuda


In [10]:
# Hyperparameter 설정
BATCH_SIZE = 64
INPUT_SIZE = 1000
HIDDEN_SIZE = 100
OUTPUT_SIZE = 10

In [19]:
# Network 정의
# torch.randn -> 평균이 0, 표준편차가 1인 정규분포에서 샘플링
x = torch.randn(BATCH_SIZE,
                INPUT_SIZE,
                device = DEVICE,
                dtype = torch.float,
                requires_grad = False)
y = torch.randn(BATCH_SIZE,
                OUTPUT_SIZE,
                device = DEVICE,
                dtype = torch.float,
                requires_grad = False)
w1 = torch.randn(INPUT_SIZE,
                 HIDDEN_SIZE,
                 device = DEVICE,
                 dtype = torch.float,
                 requires_grad = True)
w2 = torch.randn(HIDDEN_SIZE,
                 OUTPUT_SIZE,
                 device = DEVICE,
                 dtype = torch.float,
                 requires_grad = True)

In [28]:
learning_rate = 1e-6
for t in range(1, 501):
    y_pred = x.mm(w1).clamp(min = 0).mm(w2)
    
    loss = (y_pred - y).pow(2).sum()
    if t % 100 == 0:
        print("Iteration: ", t, "\t", "Loss: ", loss.item())
    loss.backward() # backpropagation
              
    with torch.no_grad(): # gradient 값 고정
        # weight parameter update
        w1 -= learning_rate * w1.grad 
        w2 -= learning_rate * w2.grad
        # gradient 초기화
        w1.grad.zero_()
        w2.grad.zero_()

Iteration:  100 	 Loss:  32.85944747924805
Iteration:  200 	 Loss:  11.868019104003906
Iteration:  300 	 Loss:  15.204971313476562
Iteration:  400 	 Loss:  27.040578842163086
Iteration:  500 	 Loss:  10.689077377319336
